export const INIT_STORE = 'INIT_STORE'
export const GET_POSITIONS = 'GET_POSITIONS'
export const SHOW_POSITION_BATCHES = 'SHOW_POSITION_BATCHES'
export const SHOW_BATCH_RESUMES = 'SHOW_BATCH_RESUMES'
